[workspace]
members = ["webapp", "client"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Jethro Djan <jthryeboah@gmail.com>"]

[workspace.dependencies]
argon2 = { version = "0.5.3" }
