name: "ridge-exam-tool"

services:
  db: 
    image: postgres:latest
    container_name: postgres-db
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      POSTGRES_DB=examtool-db
    ports:
      - "5432:5432"

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
