name: "ridge-exam-tool"

services:
  db: 
    image: postgres:latest
    container_name: postgres-db
    # networks:
    #   - "postgresnet"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: examtool-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

    # networks:
    #   postgresnet:
